/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.clienttoclient.messaging;

import org.junit.Test;

public class AppTest {

    @Test
    public void testCommandLineArguments() {

        WSC2CApplication.verifyCommandLineArgs(new String[]{"-port", "8080"});
        WSC2CApplication.verifyCommandLineArgs(new String[]{"-configpath", "./build"});
        WSC2CApplication.verifyCommandLineArgs(new String[]{
                "-port", "8080", "-configpath", "./build"});
        WSC2CApplication.verifyCommandLineArgs(new String[]{
                "-configpath", "./build", "-port", "8080"});



    }

}
